name: Deploy Jupyter Book

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install "jupyter-book<1" ghp-import
      - run: jupyter-book build .
      - run: ghp-import -n -p -f _build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}